### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by exaptis** [kmathy/cerializr#2]
Hi,

first of all thanks for providing this library, which I think is a really nice object-oriented based alternative to the functional style of mapping observable responses in order to map api responses.

Unfortunately I encountered a problem with the latest version when using it with the angular cli prod build. See my sample at https://github.com/exaptis/nx-cerializr/commit/15b619d29912aa9cadfdb274af70325920f9d3ad

1. run `ng build --prod` or `npm run build -- --prod` 
2. serve the dist build `http-server dist/apps/cerializr -o`
3. in the console the error `Uncaught TypeError: Object(...) is not a function at main-es2015...` is shown.

<img width="886" alt="Screenshot 2019-12-26 at 13 08 43" src="https://user-images.githubusercontent.com/273295/71475786-0cdb1d00-27e2-11ea-85ca-1828067112f1.png">

It only works if you skip the `--prod` step, as this will optimize and minify the bundle, but then the bundle is not suitable for production. 

It works in prod mode if I switch back to `3.0.3` before the webpack build was introduced. Can you have a look at this please, that would be great! 

Thanks and happy holidays!
David

**Comment by kmathy** [comment]
Hi @exaptis,

Thanks for submitting an issue for Cerializr!

I'm taking a look and I will see what's happening.
FYI, I don't use webpack anymore due to problem concerning the minification.

**Comment by kmathy** [comment]
It should be fixed now. (v3.1.4)
The problem was the "sideEffects: false" in package.json. It was used for Webpack compilation, and I forgot to remove it.

I installed it in your project, refresh the tab and it worked (displaying the list as JSON).
I also tried the new version in a personal project.

Let me know if everything works great for you ;)

**Comment by exaptis** [comment]
Thanks for the very quick fix - works now! Amazing speed :-) 👍
